---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: my-config
    behavior: merge
    literals:
      - MY_VAR=my-merged-value

bases:
  - "../../base"

nameSuffix: "-$(MY_VAR)"

commonLabels:
  my-var-label: $(MY_VAR)

images:
  - name: busybox
    newName: busybox
    newTag: $(MY_VAR)
